language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - pip install --no-dependencies .
  - pip install -r tests/requirements.txt
  - pip install -r tests/requirements_$TRAVIS_BRANCH.txt
  - pip install -r tests/requirements_travis.txt

script:
  - coverage run -m py.test

after_success:
  - coveralls